//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArbitroBitcoin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArbitroBitcoin.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Árbitro Bitcoin.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbitrar.
        /// </summary>
        internal static string Arbitrar {
            get {
                return ResourceManager.GetString("Arbitrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Árbitro.
        /// </summary>
        internal static string Arbitro {
            get {
                return ResourceManager.GetString("Arbitro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Árbitro Bitcoin.
        /// </summary>
        internal static string ArbitroBitcoin {
            get {
                return ResourceManager.GetString("ArbitroBitcoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assinar Transação.
        /// </summary>
        internal static string AssinarTransacao {
            get {
                return ResourceManager.GetString("AssinarTransacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço do Árbitro.
        /// </summary>
        internal static string EnderecoArbitro {
            get {
                return ResourceManager.GetString("EnderecoArbitro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de Recebimento.
        /// </summary>
        internal static string EnderecodeRecebimento {
            get {
                return ResourceManager.GetString("EnderecodeRecebimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço Arbitrado.
        /// </summary>
        internal static string EnderecodeRecebimentoArbitrado {
            get {
                return ResourceManager.GetString("EnderecodeRecebimentoArbitrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de Destino.
        /// </summary>
        internal static string EnderecoDestino {
            get {
                return ResourceManager.GetString("EnderecoDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço do Remetente.
        /// </summary>
        internal static string EnderecoRemetente {
            get {
                return ResourceManager.GetString("EnderecoRemetente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        internal static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerar Endereço.
        /// </summary>
        internal static string GerarEndereco {
            get {
                return ResourceManager.GetString("GerarEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerar Endereço Arbitrato.
        /// </summary>
        internal static string GerarEnderecodeRecebimentoArbitrado {
            get {
                return ResourceManager.GetString("GerarEnderecodeRecebimentoArbitrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar Transação.
        /// </summary>
        internal static string ImportarTransacao {
            get {
                return ResourceManager.GetString("ImportarTransacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Transação.
        /// </summary>
        internal static string ModificarTransacao {
            get {
                return ResourceManager.GetString("ModificarTransacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave Pública Árbitro.
        /// </summary>
        internal static string PubKeyArbitro {
            get {
                return ResourceManager.GetString("PubKeyArbitro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave Pública do Remetente.
        /// </summary>
        internal static string PubKeyRemetente {
            get {
                return ResourceManager.GetString("PubKeyRemetente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receber.
        /// </summary>
        internal static string Receber {
            get {
                return ResourceManager.GetString("Receber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        internal static string Sobre {
            get {
                return ResourceManager.GetString("Sobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
    }
}
